// Industry (ICP) catalog presets — the starter products / services / assemblies
// every new tenant is pre-populated with. Minimum 12 items per industry, each
// with an accurate CAD wholesale unit cost (your COGS), a sensible markup, the
// right unit of measure, and an image. Customer price is computed automatically
// from cost × (1 + markup%). Assemblies roll up their component items.
//
// Costs are grounded in 2024–2025 Canadian wholesale/contractor pricing; the
// description notes the rough USD-equivalent where useful. Numbers are starting
// points a tenant can fine-tune — never blank, never a guess presented as fact.

export type CatalogPresetKind = "service" | "product" | "assembly";

export type CatalogPresetItem = {
  /** Stable key within the industry — also used to wire assembly components. */
  key: string;
  kind: CatalogPresetKind;
  name: string;
  sku: string;
  category: string;
  description: string;
  unit: string;
  /** Your wholesale / COGS cost per unit, in CAD. Ignored for assemblies (rolled up). */
  unitCost: number;
  /** % markup over cost (auto price mode). Ignored for assemblies (rolled up). */
  markupPct: number;
  taxable: boolean;
  /** Assembly composition by component `key` + qty. */
  components?: { key: string; qty: number }[];
  /** Image search slug used at seed time to resolve a hosted image URL. */
  imageQuery: string;
  /** Resolved hosted image URL (filled in below; may be "" until sourced). */
  image: string;
};

export type CatalogPreset = Record<string, CatalogPresetItem[]>;

// NOTE: image URLs are filled in progressively via the asset pipeline. An empty
// string is safe — the catalog UI simply shows a placeholder tile.
export const CATALOG_PRESETS: CatalogPreset = {
  // ───────────────────── HOME BUILDER & RESIDENTIAL DEVELOPER ─────────────────────
  "home-builder-developer": [
    { key: "structural-option", kind: "service", name: "Structural Option Add-On (per item)", sku: "HBD-STR", category: "Selections", description: "Framing-stage structural change: extra window, layout change, basement dev shell. (~$1,200 USD typical)", unit: "each", unitCost: 900, markupPct: 40, taxable: true, imageQuery: "new home framing structural option", image: "" },
    { key: "design-studio-session", kind: "service", name: "Design-Studio Selections Session", sku: "HBD-DSS", category: "Selections", description: "Guided colour/finish selections appointment with the buyer. (~$0 direct cost, billed as part of build)", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "home design studio consultation", image: "" },
    { key: "change-order-admin", kind: "service", name: "Change Order Processing Fee", sku: "HBD-COF", category: "Change Orders", description: "Admin fee for pricing and documenting a mid-build change order. (~$150 USD typical)", unit: "each", unitCost: 60, markupPct: 90, taxable: true, imageQuery: "construction change order paperwork", image: "" },
    { key: "possession-walkthrough", kind: "service", name: "Pre-Possession Walkthrough", sku: "HBD-PWT", category: "Handoff", description: "Structured deficiency walkthrough ahead of possession day. (~$0 direct cost, included)", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "new home walkthrough inspection", image: "" },
    { key: "warranty-callback", kind: "service", name: "Warranty Service Callback", sku: "HBD-WSC", category: "Warranty", description: "1/2/10-year warranty service visit for a covered deficiency. (~$95 USD typical)", unit: "job", unitCost: 45, markupPct: 90, taxable: true, imageQuery: "home warranty repair visit", image: "" },
    { key: "flooring-upgrade-lvp", kind: "product", name: "Flooring Upgrade — LVP (per sq ft)", sku: "HBD-FLR-LVP", category: "Selections", description: "Better-tier luxury vinyl plank upgrade over builder-grade carpet. (~$4.20 USD/sqft cost)", unit: "sqft", unitCost: 5.6, markupPct: 55, taxable: true, imageQuery: "luxury vinyl plank flooring sample", image: "" },
    { key: "cabinet-upgrade-tier2", kind: "product", name: "Cabinet Upgrade — Tier 2 (per lin ft)", sku: "HBD-CAB-T2", category: "Selections", description: "Mid-tier cabinet finish upgrade over base builder cabinets. (~$85 USD/lin ft cost)", unit: "ft", unitCost: 115, markupPct: 45, taxable: true, imageQuery: "kitchen cabinet upgrade finish", image: "" },
    { key: "asm-basement-dev", kind: "assembly", name: "Basement Development Package", sku: "HBD-ASM-BSMT", category: "Selections", description: "Structural option package for finished basement shell at framing stage.", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "basement development construction", image: "", components: [{ "key": "structural-option", "qty": 1 }, { "key": "change-order-admin", "qty": 1 }] },
  ],

  // ───────────────────────── PAINTING & DECORATING ─────────────────────────
  "painting-decorating": [
    { key: "estimate-walk", kind: "service", name: "On-Site Estimate & Walkthrough", sku: "PNT-EST", category: "Estimating", description: "Production-rate measure + written estimate. (~$0 cost, sales activity)", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "painting estimate walkthrough", image: "" },
    { key: "labor", kind: "service", name: "Painter Labor (per hour)", sku: "PNT-LBR", category: "Labor", description: "Standard journeyman painter hourly rate. (~$38 USD)", unit: "hour", unitCost: 32, markupPct: 90, taxable: true, imageQuery: "painter working interior wall", image: "" },
    { key: "interior-repaint-room", kind: "service", name: "Interior Repaint — Standard Room (2 coats)", sku: "PNT-INT-RM", category: "Painting", description: "Walls + ceiling + trim, 2-coat, avg 12×12 room. (~$310 USD price)", unit: "job", unitCost: 140, markupPct: 120, taxable: true, imageQuery: "interior room repaint two coats", image: "" },
    { key: "exterior-repaint-sqft", kind: "service", name: "Exterior Repaint (per sq ft)", sku: "PNT-EXT-SF", category: "Painting", description: "Siding/stucco exterior repaint, 2-coat, per sq ft. (~$2.10 USD/sqft price)", unit: "sqft", unitCost: 1.1, markupPct: 90, taxable: true, imageQuery: "exterior house repaint siding", image: "" },
    { key: "cabinet-refinish-door", kind: "service", name: "Cabinet Refinishing (per door/drawer)", sku: "PNT-CAB", category: "Painting", description: "Spray-finish refinishing per cabinet door or drawer front. (~$45 USD price)", unit: "each", unitCost: 22, markupPct: 100, taxable: true, imageQuery: "cabinet door spray refinishing", image: "" },
    { key: "paint-gal", kind: "product", name: "Premium Interior Paint (per gal)", sku: "PNT-PNT-INT", category: "Materials", description: "Washable premium interior paint, per gallon. (~$52 USD cost)", unit: "each", unitCost: 68, markupPct: 45, taxable: true, imageQuery: "interior paint gallon can", image: "" },
    { key: "paint-ext-gal", kind: "product", name: "Exterior Paint (per gal)", sku: "PNT-PNT-EXT", category: "Materials", description: "100% acrylic exterior paint, per gallon. (~$58 USD cost)", unit: "each", unitCost: 76, markupPct: 45, taxable: true, imageQuery: "exterior acrylic paint gallon", image: "" },
    { key: "touch-up-visit", kind: "service", name: "Touch-Up / Punch List Visit", sku: "PNT-TCH", category: "Closeout", description: "Post-completion touch-up visit for punch items. (~$95 USD price)", unit: "job", unitCost: 40, markupPct: 90, taxable: true, imageQuery: "paint touch up punch list", image: "" },
    { key: "asm-interior-repaint-home", kind: "assembly", name: "Whole-Home Interior Repaint (avg 3-bed)", sku: "PNT-ASM-HOME", category: "Painting", description: "Interior repaint of an average 3-bedroom home: paint, labor.", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "whole home interior repaint", image: "", components: [{ "key": "paint-gal", "qty": 12 }, { "key": "labor", "qty": 32 }] },
  ],

  // ───────────────────────── DESIGN-BUILD RENOVATIONS & ADDITIONS ─────────────────────────
  "design-build": [
    { key: "design-retainer", kind: "service", name: "Design Agreement / Retainer", sku: "DSB-RET", category: "Design", description: "Paid design-phase retainer, credited to construction contract. (~2% of est. project cost)", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "architect design consultation", image: "" },
    { key: "selections-session", kind: "service", name: "Selections Session", sku: "DSB-SEL", category: "Selections", description: "Guided client selections appointment (fixtures, finishes). (~$0 direct cost, included)", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "interior design selections meeting", image: "" },
    { key: "labor", kind: "service", name: "Production Labor (per hour)", sku: "DSB-LBR", category: "Labor", description: "Lead carpenter / production crew hourly rate. (~$58 USD)", unit: "hour", unitCost: 48, markupPct: 90, taxable: true, imageQuery: "carpenter renovation labor", image: "" },
    { key: "change-order-admin", kind: "service", name: "Change Order Processing", sku: "DSB-COF", category: "Change Orders", description: "Pricing and documentation of a mid-project change order. (~$150 USD typical)", unit: "each", unitCost: 60, markupPct: 90, taxable: true, imageQuery: "change order document renovation", image: "" },
    { key: "draw-invoice-admin", kind: "service", name: "Draw Milestone Invoice", sku: "DSB-DRAW", category: "Billing", description: "Milestone-triggered progress draw invoice. (~$0 direct cost)", unit: "each", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "construction draw invoice milestone", image: "" },
    { key: "kitchen-allowance", kind: "product", name: "Kitchen Allowance Line (base)", sku: "DSB-ALW-KIT", category: "Allowances", description: "Base allowance placeholder for kitchen fixtures/finishes package. (~$18,000 USD typical midrange)", unit: "job", unitCost: 15000, markupPct: 20, taxable: true, imageQuery: "kitchen renovation finishes", image: "" },
    { key: "closeout-survey", kind: "service", name: "Closeout Walkthrough & Warranty Survey", sku: "DSB-CLS", category: "Closeout", description: "Final walkthrough with punch list + warranty survey scheduling. (~$0 direct cost)", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "renovation closeout walkthrough", image: "" },
  ],

  // ───────────────────────── HOME RENOVATION & GENERAL CONTRACTING ─────────────────────────
  "renovation-contractor": [
    { key: "estimate-fixed-price", kind: "service", name: "Fixed-Price Project Estimate", sku: "REN-EST", category: "Estimating", description: "Detailed fixed-price estimate with allowance line items. (~$0 cost, sales activity)", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "renovation contractor estimate", image: "" },
    { key: "labor", kind: "service", name: "Site Crew Labor (per hour)", sku: "REN-LBR", category: "Labor", description: "Site crew / carpenter hourly rate. (~$55 USD)", unit: "hour", unitCost: 46, markupPct: 90, taxable: true, imageQuery: "renovation crew working site", image: "" },
    { key: "kitchen-remodel", kind: "service", name: "Kitchen Remodel (base package)", sku: "REN-KIT", category: "Projects", description: "Full kitchen remodel base package before allowances/selections. (~$35,000 USD median)", unit: "job", unitCost: 24000, markupPct: 40, taxable: true, imageQuery: "kitchen remodel construction", image: "" },
    { key: "bathroom-remodel", kind: "service", name: "Bathroom Remodel (base package)", sku: "REN-BTH", category: "Projects", description: "Full bathroom remodel base package before allowances/selections. (~$18,000 USD median)", unit: "job", unitCost: 12500, markupPct: 40, taxable: true, imageQuery: "bathroom remodel renovation", image: "" },
    { key: "change-order-admin", kind: "service", name: "Change Order Processing", sku: "REN-COF", category: "Change Orders", description: "Pricing and documentation of a mid-project change order. (~$150 USD typical)", unit: "each", unitCost: 60, markupPct: 90, taxable: true, imageQuery: "renovation change order paperwork", image: "" },
    { key: "draw-invoice-admin", kind: "service", name: "Draw Milestone Invoice", sku: "REN-DRAW", category: "Billing", description: "Milestone-triggered progress draw invoice. (~$0 direct cost)", unit: "each", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "construction progress invoice", image: "" },
    { key: "cabinet-allowance", kind: "product", name: "Cabinet Allowance Line (base)", sku: "REN-ALW-CAB", category: "Allowances", description: "Base allowance placeholder for cabinetry package. (~$8,000 USD typical)", unit: "job", unitCost: 6500, markupPct: 20, taxable: true, imageQuery: "kitchen cabinets allowance", image: "" },
    { key: "punch-list-visit", kind: "service", name: "Punch List / Closeout Visit", sku: "REN-PNC", category: "Closeout", description: "Final punch-list resolution visit. (~$0 direct cost, included)", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "punch list final walkthrough", image: "" },
  ],

  // ───────────────────────── GARAGE DOORS ─────────────────────────
  "garage-door": [
    { key: "diagnostic", kind: "service", name: "Service Call / Diagnosis", sku: "GAR-DIAG", category: "Service", description: "Trip + fault diagnosis, credited to repair. (~$65 USD price)", unit: "job", unitCost: 40, markupPct: 110, taxable: true, imageQuery: "garage door technician diagnosis", image: "" },
    { key: "labor", kind: "service", name: "Technician Labor (per hour)", sku: "GAR-LBR", category: "Labor", description: "Garage door technician hourly rate. (~$70 USD)", unit: "hour", unitCost: 48, markupPct: 100, taxable: true, imageQuery: "garage door technician working", image: "" },
    { key: "spring-replace", kind: "service", name: "Torsion Spring Replacement", sku: "GAR-SPR", category: "Repair", description: "Broken spring replacement, standard residential door. (~$220 USD price)", unit: "job", unitCost: 95, markupPct: 130, taxable: true, imageQuery: "garage door torsion spring replacement", image: "" },
    { key: "door-basic", kind: "product", name: "Garage Door — Basic Tier (steel, non-insulated)", sku: "GAR-DOOR-1", category: "Doors", description: "Good tier: single-layer steel door. (~$780 USD cost, 16x7)", unit: "each", unitCost: 780, markupPct: 55, taxable: true, imageQuery: "steel garage door basic", image: "" },
    { key: "door-insulated", kind: "product", name: "Garage Door — Insulated Tier (R-12)", sku: "GAR-DOOR-2", category: "Doors", description: "Better tier: double-layer insulated steel door, R-12. (~$1,150 USD cost, 16x7)", unit: "each", unitCost: 1150, markupPct: 50, taxable: true, imageQuery: "insulated garage door r12", image: "" },
    { key: "door-premium", kind: "product", name: "Garage Door — Premium Tier (R-18, windows)", sku: "GAR-DOOR-3", category: "Doors", description: "Best tier: triple-layer insulated door with window inserts, R-18. (~$1,650 USD cost, 16x7)", unit: "each", unitCost: 1650, markupPct: 45, taxable: true, imageQuery: "premium garage door windows insulated", image: "" },
    { key: "opener", kind: "product", name: "Garage Door Opener (belt-drive, smart)", sku: "GAR-OPN", category: "Openers", description: "Wi-Fi belt-drive opener with smartphone control. (~$260 USD cost)", unit: "each", unitCost: 260, markupPct: 60, taxable: true, imageQuery: "smart garage door opener belt drive", image: "" },
    { key: "tune-up", kind: "service", name: "Annual Tune-Up", sku: "GAR-TUNE", category: "Maintenance", description: "Multi-point inspection, lubrication, balance check. (~$95 USD price)", unit: "job", unitCost: 42, markupPct: 110, taxable: true, imageQuery: "garage door maintenance tune up", image: "" },
    { key: "asm-door-install", kind: "assembly", name: "Door Configurator — Insulated Install", sku: "GAR-ASM-INST", category: "Installation", description: "Turn-key install: insulated door, opener + labor.", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "garage door installation crew", image: "", components: [{ "key": "door-insulated", "qty": 1 }, { "key": "opener", "qty": 1 }, { "key": "labor", "qty": 4 }] },
  ],

  // ───────────────────────── TREE CARE & ARBORIST SERVICES ─────────────────────────
  "tree-care": [
    { key: "assessment", kind: "service", name: "Arborist Site Assessment", sku: "TRE-ASMT", category: "Service", description: "On-site tree health/hazard assessment. (~$85 USD price)", unit: "job", unitCost: 40, markupPct: 110, taxable: true, imageQuery: "arborist tree assessment", image: "" },
    { key: "labor", kind: "service", name: "Crew Labor (per hour)", sku: "TRE-LBR", category: "Labor", description: "Ground crew hourly rate. (~$52 USD)", unit: "hour", unitCost: 40, markupPct: 90, taxable: true, imageQuery: "tree care crew working", image: "" },
    { key: "removal-small", kind: "service", name: "Tree Removal — Small/Medium", sku: "TRE-RMV-SM", category: "Tree Care", description: "Removal of a small-to-medium tree (<40 ft). (~$650 USD price)", unit: "job", unitCost: 320, markupPct: 100, taxable: true, imageQuery: "tree removal small crew", image: "" },
    { key: "removal-large", kind: "service", name: "Tree Removal — Large (crane-assisted)", sku: "TRE-RMV-LG", category: "Tree Care", description: "Large tree removal requiring crane/rigging. (~$1,800 USD price)", unit: "job", unitCost: 950, markupPct: 90, taxable: true, imageQuery: "large tree removal crane", image: "" },
    { key: "pruning-standard", kind: "service", name: "Pruning / Trimming — Standard", sku: "TRE-PRN", category: "Tree Care", description: "Standard prune/trim visit, per tree. (~$220 USD price)", unit: "each", unitCost: 100, markupPct: 110, taxable: true, imageQuery: "tree pruning trimming crew", image: "" },
    { key: "phc-treatment", kind: "service", name: "Plant Health Care Treatment", sku: "TRE-PHC", category: "PHC", description: "Fertilization/pest/disease treatment visit. (~$120 USD price)", unit: "job", unitCost: 55, markupPct: 110, taxable: true, imageQuery: "tree plant health care treatment", image: "" },
    { key: "stump-grind", kind: "service", name: "Stump Grinding", sku: "TRE-STMP", category: "Tree Care", description: "Mechanical stump grinding, per stump. (~$140 USD price)", unit: "each", unitCost: 65, markupPct: 110, taxable: true, imageQuery: "stump grinding machine", image: "" },
    { key: "cabling-kit", kind: "product", name: "Cabling & Bracing Kit", sku: "TRE-CBL", category: "Materials", description: "Steel cable + hardware for structural tree support. (~$85 USD cost)", unit: "each", unitCost: 110, markupPct: 60, taxable: true, imageQuery: "tree cabling bracing hardware", image: "" },
    { key: "asm-removal-cleanup", kind: "assembly", name: "Tree Removal + Cleanup", sku: "TRE-ASM-RMV", category: "Tree Care", description: "Full-service removal: removal, stump grind + labor.", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "tree removal stump cleanup", image: "", components: [{ "key": "removal-small", "qty": 1 }, { "key": "stump-grind", "qty": 1 }, { "key": "labor", "qty": 2 }] },
  ],

  // ───────────────────────── CONCRETE & FOUNDATION REPAIR ─────────────────────────
  "concrete-foundation-repair": [
    { key: "inspection", kind: "service", name: "Structural Inspection", sku: "CFR-INSP", category: "Inspection", description: "Foundation/structural inspection + report. (~$180 USD price)", unit: "job", unitCost: 85, markupPct: 110, taxable: true, imageQuery: "foundation structural inspection", image: "" },
    { key: "labor", kind: "service", name: "Crew Labor (per hour)", sku: "CFR-LBR", category: "Labor", description: "Concrete/foundation crew hourly rate. (~$58 USD)", unit: "hour", unitCost: 46, markupPct: 90, taxable: true, imageQuery: "concrete crew working foundation", image: "" },
    { key: "pier-install", kind: "service", name: "Helical Pier Installation (per pier)", sku: "CFR-PIER", category: "Foundation Repair", description: "Helical pier install for foundation underpinning, per pier. (~$1,400 USD price)", unit: "each", unitCost: 750, markupPct: 85, taxable: true, imageQuery: "helical pier foundation underpinning", image: "" },
    { key: "waterproofing-sqft", kind: "service", name: "Basement Waterproofing (per ln ft, exterior)", sku: "CFR-WTRP", category: "Waterproofing", description: "Exterior foundation waterproofing membrane, per linear foot. (~$140 USD/ft price)", unit: "ft", unitCost: 78, markupPct: 80, taxable: true, imageQuery: "basement exterior waterproofing membrane", image: "" },
    { key: "weeping-tile", kind: "service", name: "Weeping Tile Repair (per ln ft)", sku: "CFR-WPT", category: "Waterproofing", description: "Weeping tile replacement/repair, per linear foot. (~$95 USD/ft price)", unit: "ft", unitCost: 52, markupPct: 80, taxable: true, imageQuery: "weeping tile drainage repair", image: "" },
    { key: "driveway-pour-sqft", kind: "service", name: "Driveway / Pad Pour (per sq ft)", sku: "CFR-DRWY", category: "Flatwork", description: "Concrete driveway or garage pad, formed and poured, per sq ft. (~$9 USD/sqft price)", unit: "sqft", unitCost: 5.4, markupPct: 65, taxable: true, imageQuery: "concrete driveway pour", image: "" },
    { key: "engineer-signoff", kind: "service", name: "Engineer Sign-Off", sku: "CFR-ENG", category: "Inspection", description: "Third-party structural engineer sign-off for permitted repair. (~$450 USD, pass-through)", unit: "job", unitCost: 400, markupPct: 12, taxable: true, imageQuery: "structural engineer sign off report", image: "" },
    { key: "asm-pier-package", kind: "assembly", name: "Foundation Pier Package (8 piers)", sku: "CFR-ASM-PIER", category: "Foundation Repair", description: "Standard 8-pier underpinning package with engineer sign-off.", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "foundation pier installation package", image: "", components: [{ "key": "pier-install", "qty": 8 }, { "key": "engineer-signoff", "qty": 1 }, { "key": "inspection", "qty": 1 }] },
  ],

  // ───────────────────────── COMMERCIAL BUILDING MAINTENANCE CONTRACTOR ─────────────────────────
  "commercial-building-maintenance": [
    { key: "pm-visit", kind: "service", name: "Recurring PM Visit", sku: "CBM-PM", category: "Preventive Maintenance", description: "Scheduled preventive-maintenance site visit under contract. (~$0 direct cost, contract billed)", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "facility preventive maintenance visit", image: "" },
    { key: "labor", kind: "service", name: "Technician Labor (per hour)", sku: "CBM-LBR", category: "Labor", description: "Multi-trade maintenance technician hourly rate. (~$62 USD)", unit: "hour", unitCost: 50, markupPct: 90, taxable: true, imageQuery: "facility maintenance technician working", image: "" },
    { key: "work-order-general", kind: "service", name: "Work Order — General Repair", sku: "CBM-WO", category: "Work Orders", description: "Standard reactive work-order repair visit. (~$140 USD price)", unit: "job", unitCost: 65, markupPct: 100, taxable: true, imageQuery: "commercial building repair work order", image: "" },
    { key: "emergency-sla", kind: "service", name: "Emergency SLA Dispatch", sku: "CBM-EMG", category: "Emergency", description: "After-hours/emergency SLA-triggered dispatch. (~$260 USD price)", unit: "job", unitCost: 120, markupPct: 100, taxable: true, imageQuery: "emergency facility dispatch technician", image: "" },
    { key: "site-inspection", kind: "service", name: "Site Inspection / QBR Walk", sku: "CBM-INSP", category: "Inspection", description: "Quarterly business review site walk + report. (~$0 direct cost, contract billed)", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "commercial site inspection walk", image: "" },
    { key: "nte-parts-allowance", kind: "product", name: "Not-to-Exceed Parts Allowance (base)", sku: "CBM-NTE", category: "Approvals", description: "Placeholder allowance line for parts/materials requiring owner approval above NTE threshold. (~$300 USD typical)", unit: "job", unitCost: 250, markupPct: 20, taxable: true, imageQuery: "facility maintenance parts approval", image: "" },
  ],

  // ───────────────────────── FLOORING ─────────────────────────
  "flooring": [
    { key: "estimate-measure", kind: "service", name: "Flooring Estimate & Measure", sku: "FLR-EST", category: "Estimating", description: "On-site measure + material/tier estimate. (~$0 cost, sales activity)", unit: "job", unitCost: 0, markupPct: 0, taxable: false, imageQuery: "flooring estimate measurement", image: "" },
    { key: "labor-install", kind: "service", name: "Installer Labor (per sq ft)", sku: "FLR-LBR", category: "Labor", description: "Standard installation labor, per sq ft. (~$1.80 USD/sqft price)", unit: "sqft", unitCost: 1.1, markupPct: 65, taxable: true, imageQuery: "flooring installer working", image: "" },
    { key: "flooring-good", kind: "product", name: "Flooring — Good Tier (builder-grade carpet, per sq ft)", sku: "FLR-GOOD", category: "Materials", description: "Good tier: standard builder-grade carpet. (~$1.60 USD/sqft cost)", unit: "sqft", unitCost: 1.6, markupPct: 55, taxable: true, imageQuery: "builder grade carpet flooring", image: "" },
    { key: "flooring-better", kind: "product", name: "Flooring — Better Tier (LVP, per sq ft)", sku: "FLR-BETTER", category: "Materials", description: "Better tier: luxury vinyl plank. (~$3.20 USD/sqft cost)", unit: "sqft", unitCost: 3.2, markupPct: 50, taxable: true, imageQuery: "luxury vinyl plank flooring", image: "" },
    { key: "flooring-best", kind: "product", name: "Flooring — Best Tier (engineered hardwood, per sq ft)", sku: "FLR-BEST", category: "Materials", description: "Best tier: engineered hardwood. (~$6.50 USD/sqft cost)", unit: "sqft", unitCost: 6.5, markupPct: 45, taxable: true, imageQuery: "engineered hardwood flooring", image: "" },
    { key: "moisture-test", kind: "service", name: "Subfloor Moisture Test", sku: "FLR-MOIST", category: "Site Readiness", description: "Pre-install subfloor moisture test — gates scheduling. (~$45 USD price)", unit: "job", unitCost: 20, markupPct: 120, taxable: true, imageQuery: "subfloor moisture test flooring", image: "" },
    { key: "asm-lvp-room", kind: "assembly", name: "LVP Install — Average Room", sku: "FLR-ASM-LVP", category: "Installation", description: "Better-tier LVP installed in an average 12x14 room.", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "lvp flooring installation room", image: "", components: [{ "key": "flooring-better", "qty": 168 }, { "key": "labor-install", "qty": 168 }, { "key": "moisture-test", "qty": 1 }] },
  ],

  // ───────────────────────── HVAC & PLUMBING ─────────────────────────
  "hvac-plumbing": [
    { key: "diagnostic", kind: "service", name: "Diagnostic / Service Call", sku: "HVAC-DIAG", category: "Service", unit: "job", unitCost: 45, markupPct: 110, taxable: true, imageQuery: "hvac technician diagnostic service call", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F1dG7W6-3ZBZVTLTAxFtC2%2Fhvac-technician-diagnostic-service-call_1.jpg", description: "Flat-rate trip + system diagnosis. Applied to repair if work proceeds. (~$70 USD)" },
    { key: "labor", kind: "service", name: "HVAC Labor (per hour)", sku: "HVAC-LBR", category: "Labor", unit: "hour", unitCost: 55, markupPct: 100, taxable: true, imageQuery: "hvac technician working on furnace", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F2E0g4ITU_55ia0JQEjC3H%2Fhvac-technician-working-on-furnace_3.jpg", description: "Standard skilled technician labor rate, billed hourly. (~$80 USD)" },
    { key: "tuneup", kind: "service", name: "Seasonal Tune-Up", sku: "HVAC-TUNE", category: "Maintenance", unit: "job", unitCost: 60, markupPct: 130, taxable: true, imageQuery: "hvac maintenance tune up technician", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FFN3pqT2y_xGpsEOPVsQOC%2Fhvac-maintenance-tune-up-technician_1.jpg", description: "Multi-point clean & inspect for furnace or AC. (~$105 USD price)" },
    { key: "capacitor", kind: "product", name: "Run Capacitor (dual 45/5 µF)", sku: "HVAC-CAP", category: "Parts", unit: "each", unitCost: 14, markupPct: 220, taxable: true, imageQuery: "hvac dual run capacitor", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FWpXQLZgsODQszLoppSY0n%2Fhvac-dual-run-capacitor_8.jpg", description: "Common dual-run capacitor for condenser fan + compressor. (~$10 USD cost)" },
    { key: "contactor", kind: "product", name: "Contactor (40A, 24V coil)", sku: "HVAC-CONT", category: "Parts", unit: "each", unitCost: 22, markupPct: 180, taxable: true, imageQuery: "hvac contactor 40 amp", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FsP_DhWfaDrCt63a1X1OaI%2Fhvac-contactor-40-amp_0.jpg", description: "Definite-purpose contactor for condensing units. (~$16 USD cost)" },
    { key: "blower", kind: "product", name: "Blower Motor (1/2 HP ECM)", sku: "HVAC-BLWR", category: "Parts", unit: "each", unitCost: 230, markupPct: 70, taxable: true, imageQuery: "hvac blower motor ecm", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FIftN-BXVxlWMQXbaHOLOV%2Fhvac-blower-motor-ecm_3.jpg", description: "Variable-speed ECM blower motor replacement. (~$170 USD cost)" },
    { key: "thermostat", kind: "product", name: "Smart Thermostat (Wi-Fi)", sku: "HVAC-TSTAT", category: "Controls", unit: "each", unitCost: 130, markupPct: 60, taxable: true, imageQuery: "smart wifi thermostat", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FGHqE7Sx1_QPQfO5DHt6yP%2Fsmart-wifi-thermostat_7.jpg", description: "Programmable Wi-Fi thermostat (Ecobee/Nest class). (~$95 USD cost)" },
    { key: "filter", kind: "product", name: "Pleated Air Filter (16×25×1)", sku: "HVAC-FLT", category: "Consumables", unit: "each", unitCost: 6, markupPct: 150, taxable: true, imageQuery: "pleated hvac air filter", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FIted8VVajk4zS6r_OsOxQ%2Fpleated-hvac-air-filter_6.jpg", description: "MERV 11 pleated filter. (~$4.50 USD cost)" },
    { key: "furnace", kind: "product", name: "Gas Furnace (96% AFUE, 60k BTU)", sku: "HVAC-FURN", category: "Equipment", unit: "each", unitCost: 1850, markupPct: 45, taxable: true, imageQuery: "high efficiency gas furnace unit", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FHKyVbTa20ernxlMGk1oCA%2Fhigh-efficiency-gas-furnace-unit_6.png", description: "High-efficiency two-stage residential furnace. (~$1,350 USD cost)" },
    { key: "condenser", kind: "product", name: "AC Condenser (2.5 ton, 14 SEER2)", sku: "HVAC-COND", category: "Equipment", unit: "each", unitCost: 1750, markupPct: 45, taxable: true, imageQuery: "air conditioner condenser unit outdoor", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F9OrmCFp_3qxkV2kuVyLkf%2Fair-conditioner-condenser-unit-outdoor_1.jpg", description: "Outdoor condensing unit, 2.5 ton residential. (~$1,300 USD cost)" },
    { key: "asm-furnace-install", kind: "assembly", name: "Furnace Supply & Install", sku: "HVAC-ASM-FURN", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "furnace installation technician", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FeSUyARHz9s9xIMJjQejLK%2Ffurnace-installation-technician_4.jpg", description: "Turn-key high-efficiency furnace replacement: unit, thermostat, filter + labor.", components: [{ key: "furnace", qty: 1 }, { key: "thermostat", qty: 1 }, { key: "filter", qty: 1 }, { key: "labor", qty: 6 }] },
    { key: "asm-ac-install", kind: "assembly", name: "AC Supply & Install", sku: "HVAC-ASM-AC", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "air conditioner installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F4zeudOIrcLaC-jYOch9vr%2Fair-conditioner-installation_0.jpg", description: "Complete central AC install: condenser, contactor, capacitor + labor.", components: [{ key: "condenser", qty: 1 }, { key: "contactor", qty: 1 }, { key: "capacitor", qty: 1 }, { key: "labor", qty: 5 }] },
    { key: "diagnostic-plumb", kind: "service", name: "Service Call / Diagnosis", sku: "PLM-DIAG", category: "Service", unit: "job", unitCost: 45, markupPct: 110, taxable: true, imageQuery: "plumber service call diagnosis", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fjr4ncwpFtpvXYUfkYoLPy%2Fplumber-service-call-diagnosis_5.jpg", description: "Trip charge + leak/fault diagnosis. (~$70 USD)" },
    { key: "labor-plumb", kind: "service", name: "Plumbing Labor (per hour)", sku: "PLM-LBR", category: "Labor", unit: "hour", unitCost: 55, markupPct: 100, taxable: true, imageQuery: "plumber working under sink", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FziITCcxLLKugUoZqkWT43%2Fplumber-working-under-sink_1.jpg", description: "Licensed plumber hourly labor. (~$80 USD)" },
    { key: "drain", kind: "service", name: "Drain Cleaning / Snaking", sku: "PLM-DRN", category: "Service", unit: "job", unitCost: 50, markupPct: 200, taxable: true, imageQuery: "drain cleaning auger plumbing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FktjlHhAztJum7mcjkm7m9%2Fdrain-cleaning-auger-plumbing_1.jpg", description: "Mechanical auger drain clearing, single fixture. (~$150 USD price)" },
    { key: "wax", kind: "product", name: "Toilet Wax Ring Kit", sku: "PLM-WAX", category: "Parts", unit: "each", unitCost: 5, markupPct: 200, taxable: true, imageQuery: "toilet wax ring kit", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F5jNH9VpJFcuYFW0TMFpuX%2Ftoilet-wax-ring-kit_0.jpg", description: "Wax ring + bolts for toilet reseat. (~$3.50 USD cost)" },
    { key: "supply", kind: "product", name: "Braided Supply Line (1/2 in)", sku: "PLM-SUP", category: "Parts", unit: "each", unitCost: 7, markupPct: 170, taxable: true, imageQuery: "braided water supply line plumbing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fznov7H3W--LABFe6nj951%2Fbraided-water-supply-line-plumbing_1.jpg", description: "Stainless braided flexible supply line. (~$5 USD cost)" },
    { key: "shutoff", kind: "product", name: "Quarter-Turn Shutoff Valve", sku: "PLM-VLV", category: "Parts", unit: "each", unitCost: 9, markupPct: 160, taxable: true, imageQuery: "quarter turn shutoff valve plumbing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F84oM1cHwCgDelFQJiry9N%2Fquarter-turn-shutoff-valve-plumbing_1.jpg", description: "1/4-turn angle stop valve. (~$6.50 USD cost)" },
    { key: "faucet", kind: "product", name: "Kitchen Faucet (single-handle)", sku: "PLM-FCT", category: "Fixtures", unit: "each", unitCost: 95, markupPct: 70, taxable: true, imageQuery: "single handle kitchen faucet", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FT0ZOej4_nK-eMou5qthD6%2Fsingle-handle-kitchen-faucet_5.png", description: "Pull-down single-handle kitchen faucet. (~$70 USD cost)" },
    { key: "toilet", kind: "product", name: "Two-Piece Toilet (1.28 GPF)", sku: "PLM-TLT", category: "Fixtures", unit: "each", unitCost: 180, markupPct: 60, taxable: true, imageQuery: "two piece toilet white", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FAMH9zz6FhPlOLCUR-InmD%2Ftwo-piece-toilet-white_1.jpg", description: "Water-efficient elongated toilet. (~$135 USD cost)" },
    { key: "heater", kind: "product", name: "Water Heater (50 gal gas)", sku: "PLM-WH", category: "Equipment", unit: "each", unitCost: 1100, markupPct: 50, taxable: true, imageQuery: "tank water heater 50 gallon gas", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FbeCiNC7dBBX_pEjeFifCq%2Ftank-water-heater-50-gallon-gas_2.jpg", description: "50-gallon atmospheric-vent natural gas water heater. (~$820 USD cost)" },
    { key: "sump", kind: "product", name: "Sump Pump (1/3 HP)", sku: "PLM-SUMP", category: "Equipment", unit: "each", unitCost: 145, markupPct: 65, taxable: true, imageQuery: "submersible sump pump", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fe68eHDBtZZnQeA1fBi1Ff%2Fsubmersible-sump-pump_0.jpg", description: "Cast-iron submersible sump pump. (~$108 USD cost)" },
    { key: "asm-wh-install", kind: "assembly", name: "Water Heater Supply & Install", sku: "PLM-ASM-WH", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "water heater installation plumber", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FaT7htJ-pgGXFm1j-0w-vK%2Fwater-heater-installation-plumber_3.jpg", description: "Remove & replace tank water heater: unit, supply lines, shutoff + labor.", components: [{ key: "heater", qty: 1 }, { key: "supply", qty: 2 }, { key: "shutoff", qty: 1 }, { key: "labor-plumb", qty: 4 }] },
    { key: "asm-toilet-install", kind: "assembly", name: "Toilet Supply & Install", sku: "PLM-ASM-TLT", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "toilet installation bathroom", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F8ib8luDy0KIoGpnOxasJU%2Ftoilet-installation-bathroom_8.jpg", description: "New toilet set: bowl, wax ring, supply line + labor.", components: [{ key: "toilet", qty: 1 }, { key: "wax", qty: 1 }, { key: "supply", qty: 1 }, { key: "labor-plumb", qty: 1.5 }] },
  ],

  // ────────────────────── ELECTRICAL ──────────────────────
  "electrical": [
    { key: "diagnostic", kind: "service", name: "Service Call / Troubleshoot", sku: "ELE-DIAG", category: "Service", unit: "job", unitCost: 50, markupPct: 110, taxable: true, imageQuery: "electrician troubleshooting panel", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fjzvf2R-_LqOfxDUdtZ_EU%2Felectrician-troubleshooting-panel_7.jpg", description: "Trip + fault-finding diagnosis. (~$75 USD)" },
    { key: "labor", kind: "service", name: "Electrician Labor (per hour)", sku: "ELE-LBR", category: "Labor", unit: "hour", unitCost: 60, markupPct: 100, taxable: true, imageQuery: "electrician working wiring", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FPUlEerYW7KMKjsR7BxgYg%2Felectrician-working-wiring_5.jpg", description: "Licensed electrician hourly labor. (~$88 USD)" },
    { key: "inspection", kind: "service", name: "Electrical Safety Inspection", sku: "ELE-INSP", category: "Service", unit: "job", unitCost: 65, markupPct: 130, taxable: true, imageQuery: "electrical inspection home", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F3Yr7uknSZMHuVf9SJz1iI%2Felectrical-inspection-home_6.jpg", description: "Whole-home safety inspection + report. (~$110 USD price)" },
    { key: "receptacle", kind: "product", name: "Tamper-Resistant Receptacle", sku: "ELE-RCP", category: "Parts", unit: "each", unitCost: 3, markupPct: 200, taxable: true, imageQuery: "electrical outlet receptacle white", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FfilvyvY8d-1BF2Kp9keQe%2Felectrical-outlet-receptacle-white_0.jpg", description: "15A TR duplex receptacle. (~$2.20 USD cost)" },
    { key: "gfci", kind: "product", name: "GFCI Receptacle (20A)", sku: "ELE-GFCI", category: "Parts", unit: "each", unitCost: 18, markupPct: 130, taxable: true, imageQuery: "gfci outlet receptacle", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FFykqCtwd58k1ArNeAndCa%2Fgfci-outlet-receptacle_0.jpg", description: "20A GFCI protected receptacle. (~$13 USD cost)" },
    { key: "breaker", kind: "product", name: "Circuit Breaker (single-pole 20A)", sku: "ELE-BRK", category: "Parts", unit: "each", unitCost: 12, markupPct: 150, taxable: true, imageQuery: "circuit breaker single pole", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FiHwNdb9cRI-04C2in5kp5%2Fcircuit-breaker-single-pole_1.jpg", description: "Standard single-pole breaker. (~$9 USD cost)" },
    { key: "wire", kind: "product", name: "NMD90 Wire 14/2 (per ft)", sku: "ELE-WIRE", category: "Materials", unit: "ft", unitCost: 0.9, markupPct: 120, taxable: true, imageQuery: "electrical romex wire roll", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FO7LkOmhi4IkQpHeQzySgm%2Felectrical-romex-wire-roll_1.jpg", description: "Copper NMD90 14/2 building wire. (~$0.66 USD/ft cost)" },
    { key: "led", kind: "product", name: "LED Recessed Light (6 in)", sku: "ELE-LED", category: "Fixtures", unit: "each", unitCost: 14, markupPct: 110, taxable: true, imageQuery: "led recessed pot light", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FMlNH7t0Uq9tzBXfcLscVs%2Fled-recessed-pot-light_4.jpg", description: "Dimmable 6-inch LED pot light. (~$10 USD cost)" },
    { key: "panel", kind: "product", name: "Main Breaker Panel (100A, 24-space)", sku: "ELE-PNL", category: "Equipment", unit: "each", unitCost: 165, markupPct: 70, taxable: true, imageQuery: "electrical breaker panel load center", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FKN3YrWpNWYmjuksbYs94T%2Felectrical-breaker-panel-load-center_1.jpg", description: "100A indoor main breaker load centre. (~$122 USD cost)" },
    { key: "evcharger", kind: "product", name: "EV Charger (Level 2, 40A)", sku: "ELE-EVC", category: "Equipment", unit: "each", unitCost: 520, markupPct: 50, taxable: true, imageQuery: "level 2 ev charger wall", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FlxSIa8LWI_gS5Fuv5PGcI%2Flevel-2-ev-charger-wall_1.jpg", description: "Hardwired 40A Level-2 EV charging station. (~$385 USD cost)" },
    { key: "asm-panel-upgrade", kind: "assembly", name: "100A Panel Upgrade", sku: "ELE-ASM-PNL", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "electrical panel upgrade installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FSVQNzBAwfC9vdVn2ZQEia%2Felectrical-panel-upgrade-installation_2.jpg", description: "Service panel replacement: panel, breakers, wire + labor + inspection.", components: [{ key: "panel", qty: 1 }, { key: "breaker", qty: 8 }, { key: "wire", qty: 40 }, { key: "labor", qty: 8 }, { key: "inspection", qty: 1 }] },
    { key: "asm-ev-install", kind: "assembly", name: "EV Charger Install", sku: "ELE-ASM-EV", category: "Installation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "ev charger installation garage", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F__f_7xD2E5zqmTvBTUY8Q%2Fev-charger-installation-garage_4.jpg", description: "Level-2 EV charger install: charger, breaker, wire + labor.", components: [{ key: "evcharger", qty: 1 }, { key: "breaker", qty: 1 }, { key: "wire", qty: 30 }, { key: "labor", qty: 4 }] },
  ],

  // ───────────────────────── ROOFING, SIDING & EXTERIORS ─────────────────────────
  "exteriors": [
    { key: "inspection", kind: "service", name: "Roof Inspection", sku: "ROF-INSP", category: "Service", unit: "job", unitCost: 50, markupPct: 130, taxable: true, imageQuery: "roof inspection contractor", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F0zq-g7-E5LKSfdQVNqR4Z%2Froof-inspection-contractor_2.jpg", description: "Full roof inspection + condition report. (~$115 USD price)" },
    { key: "labor", kind: "service", name: "Roofing Labor (per hour)", sku: "ROF-LBR", category: "Labor", unit: "hour", unitCost: 45, markupPct: 100, taxable: true, imageQuery: "roofer working on roof", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FoCStHQ4kwnBYoC-R3QA64%2Froofer-working-on-roof_0.jpg", description: "Roofing crew hourly labor (per worker). (~$66 USD)" },
    { key: "teardown", kind: "service", name: "Tear-Off / Disposal (per sq)", sku: "ROF-TEAR", category: "Service", unit: "each", unitCost: 35, markupPct: 110, taxable: true, imageQuery: "roof tear off shingle removal", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FzvxQNHLSeybEMue8uH-Me%2Froof-tear-off-shingle-removal_4.jpg", description: "Remove + dispose old roofing, per roofing square (100 sq ft). (~$74 USD price)" },
    { key: "shingles", kind: "product", name: "Architectural Shingles (per sq)", sku: "ROF-SHG", category: "Materials", unit: "each", unitCost: 110, markupPct: 60, taxable: true, imageQuery: "architectural asphalt shingles bundle", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fz7SDIbc3BZBWMuBieJYKj%2Farchitectural-asphalt-shingles-bundle_1.jpg", description: "Laminated architectural shingles, per square (3 bundles). (~$82 USD cost)" },
    { key: "underlayment", kind: "product", name: "Synthetic Underlayment (roll)", sku: "ROF-UND", category: "Materials", unit: "roll", unitCost: 78, markupPct: 55, taxable: true, imageQuery: "synthetic roof underlayment roll", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FX8abLzUsmb0VXP_K0CJwI%2Fsynthetic-roof-underlayment-roll_1.jpg", description: "10 sq synthetic underlayment roll. (~$58 USD cost)" },
    { key: "iceshield", kind: "product", name: "Ice & Water Shield (roll)", sku: "ROF-ICE", category: "Materials", unit: "roll", unitCost: 95, markupPct: 55, taxable: true, imageQuery: "ice and water shield membrane roll", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FHebWevGB_zBc71sqLFG99%2Fice-and-water-shield-membrane-roll_0.jpg", description: "Self-adhered ice & water membrane, 2 sq. (~$70 USD cost)" },
    { key: "dripedge", kind: "product", name: "Aluminum Drip Edge (10 ft)", sku: "ROF-DRP", category: "Materials", unit: "each", unitCost: 9, markupPct: 90, taxable: true, imageQuery: "aluminum drip edge roofing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F9cwJnPxKupZR7veJeVvyf%2Faluminum-drip-edge-roofing_3.jpg", description: "10-ft aluminum drip-edge flashing. (~$6.70 USD cost)" },
    { key: "ridgevent", kind: "product", name: "Ridge Vent (4 ft)", sku: "ROF-RDG", category: "Materials", unit: "each", unitCost: 14, markupPct: 90, taxable: true, imageQuery: "roof ridge vent", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FST4kQTlqx_qNkyvPL4UJx%2Froof-ridge-vent_8.jpg", description: "4-ft rolled ridge ventilation. (~$10 USD cost)" },
    { key: "boot", kind: "product", name: "Pipe Boot Flashing", sku: "ROF-BOOT", category: "Materials", unit: "each", unitCost: 8, markupPct: 110, taxable: true, imageQuery: "roof pipe boot flashing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FOOEoKh2X2WyELWs1scbs-%2Froof-pipe-boot-flashing_6.png", description: "Rubber pipe-boot roof flashing. (~$6 USD cost)" },
    { key: "nails", kind: "product", name: "Roofing Nails (box)", sku: "ROF-NAIL", category: "Consumables", unit: "box", unitCost: 22, markupPct: 80, taxable: true, imageQuery: "roofing coil nails box", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fz2-af0TCttrUhIksIXpbV%2Froofing-coil-nails-box_0.jpg", description: "Coil roofing nails, 7,200/box. (~$16 USD cost)" },
    { key: "asm-reroof", kind: "assembly", name: "Re-Roof (per square, installed)", sku: "ROF-ASM-RE", category: "Installation", unit: "each", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "asphalt shingle roof installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FsnNqjeBoFTge9aMBRBz_I%2Fasphalt-shingle-roof-installation_5.jpg", description: "Installed re-roof per square: tear-off, underlayment, shingles, accessories + labor.", components: [{ key: "teardown", qty: 1 }, { key: "underlayment", qty: 0.1 }, { key: "shingles", qty: 1 }, { key: "dripedge", qty: 1.2 }, { key: "nails", qty: 0.1 }, { key: "labor", qty: 2.5 }] },
    { key: "asm-leak-repair", kind: "assembly", name: "Roof Leak Repair", sku: "ROF-ASM-LK", category: "Repair", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "roof leak repair flashing", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FCBz7iQbBvw0018kSEBIVK%2Froof-leak-repair-flashing_0.jpg", description: "Targeted leak repair: flashing, boot, shingles + labor + inspection.", components: [{ key: "boot", qty: 1 }, { key: "shingles", qty: 0.2 }, { key: "labor", qty: 2 }, { key: "inspection", qty: 1 }] },
  ],

  // ───────── LANDSCAPING & SNOW REMOVAL ─────────
  "landscaping-grounds-snow": [
    { key: "mowing", kind: "service", name: "Lawn Mowing (avg lot)", sku: "LND-MOW", category: "Maintenance", unit: "job", unitCost: 18, markupPct: 120, taxable: true, imageQuery: "lawn mowing landscaping crew", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FisE_6IVKYI2lqCuCCdlY_%2Flawn-mowing-landscaping-crew_5.jpg", description: "Mow, trim & edge average residential lot. (~$40 USD price)" },
    { key: "labor", kind: "service", name: "Landscaping Labor (per hour)", sku: "LND-LBR", category: "Labor", unit: "hour", unitCost: 28, markupPct: 100, taxable: true, imageQuery: "landscaper working garden", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FudwzEiMQyLii5JNtfpaH_%2Flandscaper-working-garden_4.jpg", description: "Crew member hourly labor. (~$41 USD)" },
    { key: "cleanup", kind: "service", name: "Seasonal Cleanup", sku: "LND-CLN", category: "Maintenance", unit: "job", unitCost: 70, markupPct: 110, taxable: true, imageQuery: "yard cleanup leaves landscaping", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FrtEK6Bvs6w-5mjeeO4Jf7%2Fyard-cleanup-leaves-landscaping_2.jpg", description: "Spring/fall yard cleanup + haul-away. (~$155 USD price)" },
    { key: "snow", kind: "service", name: "Snow Clearing (per visit)", sku: "LND-SNOW", category: "Seasonal", unit: "job", unitCost: 25, markupPct: 120, taxable: true, imageQuery: "snow plowing driveway", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F_X6ZdEMf2Pitr0QtZVkdM%2Fsnow-plowing-driveway_2.jpg", description: "Driveway + walkway snow clearing per visit. (~$55 USD price)" },
    { key: "mulch", kind: "product", name: "Mulch (per yard)", sku: "LND-MLC", category: "Materials", unit: "each", unitCost: 32, markupPct: 80, taxable: true, imageQuery: "garden mulch pile", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fhkz-GdWJ5hOBV1MUbmE43%2Fgarden-mulch-pile_0.jpg", description: "Bulk hardwood mulch, per cubic yard. (~$24 USD cost)" },
    { key: "topsoil", kind: "product", name: "Topsoil (per yard)", sku: "LND-SOIL", category: "Materials", unit: "each", unitCost: 28, markupPct: 80, taxable: true, imageQuery: "topsoil garden bulk", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FkN3vineDPKeK4C9nhbUVX%2Ftopsoil-garden-bulk_3.jpg", description: "Screened topsoil, per cubic yard. (~$21 USD cost)" },
    { key: "sod", kind: "product", name: "Sod (per sq ft)", sku: "LND-SOD", category: "Materials", unit: "sqft", unitCost: 0.45, markupPct: 90, taxable: true, imageQuery: "sod grass roll lawn", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FLJwUEVSTZ8uFDhRu1q3gx%2Fsod-grass-roll-lawn_2.jpg", description: "Fresh turf sod, per sq ft. (~$0.34 USD/sqft cost)" },
    { key: "shrub", kind: "product", name: "Shrub / Plant (3 gal)", sku: "LND-SHB", category: "Plants", unit: "each", unitCost: 16, markupPct: 90, taxable: true, imageQuery: "potted shrub nursery plant", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FDgDomPgUcTMsXEYg8azvg%2Fpotted-shrub-nursery-plant_0.jpg", description: "3-gallon nursery shrub. (~$12 USD cost)" },
    { key: "paver", kind: "product", name: "Concrete Paver (per sq ft)", sku: "LND-PVR", category: "Hardscape", unit: "sqft", unitCost: 3.2, markupPct: 70, taxable: true, imageQuery: "concrete patio paver stone", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F5Nrf8kVKPhwkLRRt00edU%2Fconcrete-patio-paver-stone_6.jpg", description: "Interlocking concrete paver, per sq ft. (~$2.40 USD/sqft cost)" },
    { key: "icemelt", kind: "product", name: "Ice Melt (20 kg bag)", sku: "LND-ICE", category: "Consumables", unit: "each", unitCost: 12, markupPct: 90, taxable: true, imageQuery: "ice melt salt bag", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FT6lCWlMwsDahlEvMI98KO%2Fice-melt-salt-bag_1.jpg", description: "20 kg de-icing salt bag. (~$9 USD cost)" },
    { key: "asm-mulch-beds", kind: "assembly", name: "Mulch & Refresh Beds", sku: "LND-ASM-MLC", category: "Maintenance", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "garden bed mulch installation", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FYkqDdy4b7f2wa26rkhbJU%2Fgarden-bed-mulch-installation_0.jpg", description: "Bed refresh: mulch material + labor to spread.", components: [{ key: "mulch", qty: 3 }, { key: "labor", qty: 3 }] },
    { key: "asm-paver-patio", kind: "assembly", name: "Paver Patio (per sq ft, installed)", sku: "LND-ASM-PVR", category: "Hardscape", unit: "sqft", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "paver patio installation backyard", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FAN6mezueueme4VljP4DDI%2Fpaver-patio-installation-backyard_4.jpg", description: "Installed paver patio per sq ft: pavers, base + labor.", components: [{ key: "paver", qty: 1 }, { key: "topsoil", qty: 0.01 }, { key: "labor", qty: 0.15 }] },
  ],

  // ────────────── RESTORATION & EMERGENCY (Fire & Flood) ────────────
  "restoration": [
    { key: "assessment", kind: "service", name: "Emergency Assessment", sku: "RST-ASMT", category: "Service", unit: "job", unitCost: 60, markupPct: 130, taxable: true, imageQuery: "water damage assessment inspector", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FxvBmAHONhDvxxoDJFBDt1%2Fwater-damage-assessment-inspector_0.jpg", description: "Rapid on-site damage assessment + moisture mapping. (~$140 USD price)" },
    { key: "labor", kind: "service", name: "Restoration Labor (per hour)", sku: "RST-LBR", category: "Labor", unit: "hour", unitCost: 50, markupPct: 100, taxable: true, imageQuery: "restoration worker cleanup", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FznwZJ0nBac09grENEZaWP%2Frestoration-worker-cleanup_6.jpg", description: "Mitigation/remediation technician hourly labor. (~$74 USD)" },
    { key: "waterextract", kind: "service", name: "Water Extraction (per sq ft)", sku: "RST-EXT", category: "Mitigation", unit: "sqft", unitCost: 0.6, markupPct: 150, taxable: true, imageQuery: "water extraction flood cleanup", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F-tY-irKbLUuKQYx4fm39c%2Fwater-extraction-flood-cleanup_8.jpg", description: "Standing-water extraction, per sq ft affected. (~$0.45 USD/sqft cost)" },
    { key: "antimicrobial", kind: "product", name: "Antimicrobial Treatment (gal)", sku: "RST-AMB", category: "Consumables", unit: "gal", unitCost: 28, markupPct: 90, taxable: true, imageQuery: "antimicrobial disinfectant jug", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FIuqaPJRrvufYt_ot1f2CB%2Fantimicrobial-disinfectant-jug_3.jpg", description: "EPA-registered antimicrobial/disinfectant. (~$21 USD/gal cost)" },
    { key: "polysheet", kind: "product", name: "6-mil Poly Containment (roll)", sku: "RST-POLY", category: "Materials", unit: "roll", unitCost: 42, markupPct: 80, taxable: true, imageQuery: "plastic sheeting containment roll", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FYnD8_95fbANNQJhqiX76E%2Fplastic-sheeting-containment-roll_6.jpg", description: "10×100 ft 6-mil poly for containment barriers. (~$31 USD cost)" },
    { key: "airmover", kind: "product", name: "Air Mover / Blower (rental-day)", sku: "RST-AIR", category: "Equipment", unit: "each", unitCost: 12, markupPct: 200, taxable: true, imageQuery: "air mover blower drying fan", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FXA-wjfOIg43wYKqh7XgNP%2Fair-mover-blower-drying-fan_0.jpg", description: "Centrifugal air mover, charged per unit per day. (~$9 USD/day cost)" },
    { key: "dehumidifier", kind: "product", name: "LGR Dehumidifier (rental-day)", sku: "RST-DEH", category: "Equipment", unit: "each", unitCost: 35, markupPct: 170, taxable: true, imageQuery: "lgr commercial dehumidifier", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FJFbD9ZPGLT1T-hpPgZAmZ%2Flgr-commercial-dehumidifier_0.jpg", description: "Low-grain refrigerant dehumidifier, per day. (~$26 USD/day cost)" },
    { key: "airscrubber", kind: "product", name: "HEPA Air Scrubber (rental-day)", sku: "RST-SCR", category: "Equipment", unit: "each", unitCost: 40, markupPct: 160, taxable: true, imageQuery: "hepa air scrubber negative air machine", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F67hwAq3D6aSw1kBd3rul2%2Fhepa-air-scrubber-negative-air-machine_0.jpg", description: "HEPA air scrubber/negative-air machine, per day. (~$30 USD/day cost)" },
    { key: "ppe", kind: "product", name: "PPE Kit (Tyvek + respirator)", sku: "RST-PPE", category: "Consumables", unit: "set", unitCost: 22, markupPct: 90, taxable: true, imageQuery: "tyvek suit respirator ppe", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FgVW9jjRBWujGncNyrxtBv%2Ftyvek-suit-respirator-ppe_3.jpg", description: "Tyvek suit, gloves, half-mask respirator + filters. (~$16 USD cost)" },
    { key: "boardup", kind: "service", name: "Emergency Board-Up", sku: "RST-BRD", category: "Mitigation", unit: "job", unitCost: 90, markupPct: 120, taxable: true, imageQuery: "emergency board up window plywood", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2F4UBdmhyQnVSZovc1nDbyD%2Femergency-board-up-window-plywood_0.jpg", description: "Secure openings with plywood after loss event. (~$200 USD price)" },
    { key: "asm-water-mit", kind: "assembly", name: "Water Mitigation (avg room)", sku: "RST-ASM-WTR", category: "Mitigation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "water mitigation drying equipment room", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2FCVL7yxRmXBXHj-_eU0mdM%2Fwater-mitigation-drying-equipment-room_0.jpg", description: "3-day average-room dry-out: extraction, movers, dehu, treatment + labor.", components: [{ key: "waterextract", qty: 200 }, { key: "airmover", qty: 9 }, { key: "dehumidifier", qty: 3 }, { key: "antimicrobial", qty: 1 }, { key: "labor", qty: 6 }] },
    { key: "asm-mold-remed", kind: "assembly", name: "Mold Remediation (contained)", sku: "RST-ASM-MLD", category: "Remediation", unit: "job", unitCost: 0, markupPct: 0, taxable: true, imageQuery: "mold remediation containment worker", image: "https://storage.googleapis.com/runable-templates/cli-uploads%2FjsuksrUtFf2PxJQUiSoPHZjCvMySkt7Q%2Fvklfc3RXO5wMq4BN_RJj7%2Fmold-remediation-containment-worker_0.jpg", description: "Contained remediation: poly barrier, scrubber, PPE, antimicrobial + labor.", components: [{ key: "polysheet", qty: 1 }, { key: "airscrubber", qty: 3 }, { key: "ppe", qty: 2 }, { key: "antimicrobial", qty: 2 }, { key: "labor", qty: 10 }] },
  ],
};
