services:
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    restart: unless-stopped
    ports:
    - 8080:8080
    - 5001:5001
    environment:
      SQLD_NODE: primary
    volumes:
    - sqld-data:/var/lib/sqld
    platform: linux/amd64
  db-studio:
    image: oven/bun:alpine
    ports:
    - 4983:4983
    depends_on:
    - db
    - web
    environment:
      DATABASE_URL: http://db:8080
    entrypoint:
    - bunx
    - drizzle-kit
    - studio
    - --host
    - 0.0.0.0
    volumes:
    - ../../../..//packages/web:/app
    - node-modules:/app/node_modules
    working_dir: /app
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
    - 6379:6379
  web:
    image: oven/bun:alpine
    ports:
    - 5173:5173
    depends_on:
    - db
    - redis
    environment:
      BETTER_AUTH_URL: http://localhost:5173
      DATABASE_URL: http://db:8080
      REDIS_URL: redis://redis:6379
    entrypoint:
    - /bin/sh
    - /app/entrypoint.sh
    volumes:
    - ../../../..//packages/web:/app
    - ../../../..//dev/docker/entrypoint.sh:/app/entrypoint.sh
    - node-modules:/app/node_modules
    working_dir: /app
volumes:
  node-modules: {}
  sqld-data: {}
